### ISSUE TITLE
TTL is broke

### ISSUE THREAD

**Issue by StDako** [StDako/node-email-verification#5]
was working before, not sure why it's not working now. attempting to fix

@frankcash could you verify this by trying out the express example and changing the expiration time option to 60 seconds

**Comment by frankcash** [comment]
I will get to it tomorrow if that's okay!

**Comment by StDako** [comment]
fixed with [most recent commit](https://github.com/StDako/node-email-verification/commit/661fe4706e08612b508e47839ffc0cd316560c3c)

**Comment by frankcash** [comment]
:+1:
